name: build external libs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [ x86, x64 ]

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: ${{ matrix.arch }}
    
    - name: Install Meson
      run: |
       pip install meson

    - name: Build
      run: ./lib/external/generate.ps1

    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: external-libs-${{ matrix.arch }}
        path: cairo
