name: build external libs

on:
  push:
    branches: [ master ]
    paths: [ lib/external/generate.ps1 ]
  pull_request:
    branches: [ master ]
    paths: [ lib/external/generate.ps1 ]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [ x86, x64 ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Visual Studio shell
      uses: egor-tensin/vs-shell@v2
      with:
        arch: ${{ matrix.arch }}
    
    - name: Install Meson
      run: |
       pip install meson

    - name: Build
      run: ./lib/external/generate.ps1

    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: external-libs-${{ matrix.arch }}
        path: cairo/meson-build/install
